apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: online-event-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: qasimhassan65/devops_assignment-booking-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_URL
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: online-event-booking
spec:
  selector:
    app: booking-service
  ports:
    - port: 3002
      targetPort: 3002
